name: Tenpureto
description: Keep tenpureto template branches in sync
inputs:
  pull-request-label:
    description: Labels to assign to the created pull requests
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    PULL_REQUEST_LABEL: ${{ inputs.pull-request-label }}
branding:
  icon: git-merge
  color: blue
